### ISSUE TITLE
Conversion between a symmetric and a non-symmetric UniTensor

### ISSUE THREAD

**Issue by pcchen** [Cytnx-dev/Cytnx#136]
I would suggest to implement a conversion function between a symmetric and a non-symmetric UniTensor.

* Sometimes we need to un-pack a symmetric UniTensor into a non-symmetric UniTensor. Essentially, we need to assign zero to zero elements (due to symmetry) and assign non-zero elements based on the values in the symmetric UniTensor.

* Sometimes we construct a non-symmetric UniTensor, which has many zeros due to the symmetry. Then we would like to construct the corresponding symmetric UniTensor. If we assume the bond information is compatible, then we just need to find the proper block structure and set the elements based on values in the non-symmetric UniTensor. Also, if some element should be zero due to symmetry, but is not zero. In the converted symmetric UniTensor, we simply ignore it. 

* Why we want this? Sometimes we want to construct a symmetric UniTensor from a set of UniTensors, which are not necessarily symmetric. But we know the resulting UniTensor should be symmetric. Then it is easier to construct the non-symmetric UniTensor, then converted it to a symmetric UniTensor, by providing the symmetric bond information on the final symmetric UniTensor.

* For example, S^+ and S^- does not preserve total Sz symmetric but (S^+S^-) does. So one just construct the non-symmetric (S^+S^-), then promote it to a symmetric UniTensor.

**Comment by pcchen** [comment]
For example, suppose 
* T_SpSm is the non-symmetric UniTensor of S+S-
* T_SpSm_sym is the non-symmetric UniTensor of S+S-

We can "symmetrize" the "T_SpSm" by adding quantum number information to all the bonds.
````
T_SpSm_sym=Sym(T_SpSm_sym, Qnums for bonds)
````

Or we can first construct an empty (or zero) UniTensor T_SpSm_sym, then do something like
````
T_SpSm_sym.put_UniTensor(T_SpSm)
````

**Comment by kaihsin** [comment]
I think we need another unify way to do this, considering together with non-abelian symmetry case

**Comment by kaihsin** [comment]
I suggest we add a method `lhs.from( rhs: UniTensor, force: bool)`

1. So to convert from non-sym -> sym, one need to construct the symmetry unitensor first (so to make conversion non-ambiguous and also avoid confusion) 
2. force default is false, which will check if the violation of symetry happends. when = true, it ignore anything elements that are not in the symmetry structure.


```python

# make empty shell with zero data
bdi = Bond(BD_IN, [Qs(0)>>1,Qs(1)>>1])
bdo = bdi.redirect()
bd_v = Bond(BD_IN,[Qs(1)>>1])
T_Sp = UniTensor([bdi,bdo,bdv],labels=["in","out","aux"])

# construct dense:
Sp = zeros([2,2])
Sp[0,1] = 1
T = UniTensor(Sp)

# set elements from sym
T_Sp.from(T)

```
