### ISSUE TITLE
dytpe for random tensors

### ISSUE THREAD

**Issue by manuschneider** [Cytnx-dev/Cytnx#174]
When random.normal(), random.uniform() etc. are used to create random tensors, the data type is automatically double. It would be nice to have a dtype as an optional argument, so other types can be created as well.

Specifically, creating random complex tensors is commonly needed.

Also, creating random tensors should be mentioned in the user guide (in create a tensor).

**Comment by kaihsin** [comment]
This is implemented in dev-master
