### ISSUE TITLE
Network.removeTensors()

### ISSUE THREAD

**Issue by manuschneider** [Cytnx-dev/Cytnx#177]
It would be nice to be able to remove all tensors from a Network file but keep the index contraction order. This way, the Network can be reused. If I just use PutTensor() several times I cannot easily check if I really reset all the tensors, so calling something like Network.removeTensors() before loading the new tensors would be nice.

**Comment by kaihsin** [comment]
This is implemented on #195 with RmUniTensor() and RmUniTensors()
