### ISSUE TITLE
cytnx.LinOp - input parameter custom_f does not seem to exist

### ISSUE THREAD

**Issue by manuschneider** [Cytnx-dev/Cytnx#183]
In the guide, in "10.1.1. Pass a function" a LinearOperator is initialized:
H = cytnx.LinOp("mv",nx=4, dtype=cytnx.Type.Double, device=cytnx.Device.cpu, custom_f=myfunc)

However, the argument custom_f does not exist in v0.9.1 of Cytnx. Were there reasons to remove it? Or is this unintentionally? Either the functionality should be restored or this part has to be updated/marked as deprecated in the user guide.

**Comment by kaihsin** [comment]
This is intentional because the function signature is fixed and does not have any flexibility on C++ side so it is removed

**Comment by manuschneider** [comment]
So it is not available anymore and we recommend users to implement the matvec method instead, is that correct?

**Comment by kaihsin** [comment]
Yup
