### ISSUE TITLE
Eig and Eigh for UniTensor

### ISSUE THREAD

**Issue by chiamin** [Cytnx-dev/Cytnx#193]
So far Eig and Eigh only support Tensor but not UniTensor. We may want them to support also UniTensors.

**Comment by kaihsin** [comment]
you mean just like using rowrank and do Eig and Eigh?

**Comment by chiamin** [comment]
Yes this is what I thought, just like doing SVD. We need to at least check if it is a square matrix. Would be even better if we can check if the row index (after combination) has the same quantum number structure as the column index. Do you think this is possible?

**Comment by kaihsin** [comment]
Yes. it should be possible. We need to collect what is also missing and worth implementing

**Comment by chiamin** [comment]
I added the other functions we might want to support UniTensor in another
issue.

Kai-Hsin Wu ***@***.***> 於 2023年7月23日 週日 上午11:26寫道：

**Comment by kaihsin** [comment]
I think this support for UniTensor is not physical, and sometimes very confusing. As it will requires the input to be "square matrix". There is not much you can leverage from rowrank. 

When the input are with symmetry, even rowrank separate it into rank-2 matrix, the underlying block may not be square matrix. 

The user need to do it by themselves

**Comment by manuschneider** [comment]
I know it would be quite a bit to implement, but we could check if all blocks are square and implement eig for UniTensors. Not sure how high the priority of such an implementation should be. But if we mention eig in the paper we have to deal a lot with Tensors, where usually we hide this from the user.

**Comment by chiamin** [comment]
We have decided to use Eigh for the example, but Eig might also be useful in general. We can discuss this in the future, but I think we can close this issue.
