### ISSUE TITLE
Conj for UniTensor

### ISSUE THREAD

**Issue by chiamin** [Cytnx-dev/Cytnx#194]
I found that `Conj` seems not supporting `UniTensor`; is it true? Here is code

```
import cytnx

T = cytnx.arange(2*3*4).reshape(2,3,4)
uT = cytnx.UniTensor(T, labels=["a","b","c"])
uT2 = cytnx.linalg.Conj(uT)
print(uT)
print(uT2)
```

and the error

```
Traceback (most recent call last):
  File "/home/chiamin/project/2023/cytnx/test.py", line 5, in <module>
    uT2 = cytnx.linalg.Conj(uT)
TypeError: Conj(): incompatible function arguments. The following argument types are supported:
    1. (Tin: cytnx.cytnx.Tensor) -> cytnx.cytnx.Tensor

Invoked with:
```

Another comment. I think `Conj` should not be defined in `linalg` since it is not a linear algebra operator.

**Comment by kaihsin** [comment]
But Conj is a linear algebra operation?

**Comment by kaihsin** [comment]
currently, for UniTensor, Conj is a member function. ofc we can wrap a linalg function for it to make it consistent?

**Comment by chiamin** [comment]
For `Tensor`, `Conj` is defined in `cytnx.linalg`

```
import cytnx

T = cytnx.arange(2*3*4).reshape(2,3,4)
T2 = cytnx.linalg.Conj(T)
print(T2)
```

OK I didn't know that there is a `Conj` member function. I confirm that the following code works.

```
import cytnx

T = cytnx.arange(2*3*4).reshape(2,3,4)
uT = cytnx.UniTensor(T, labels=["a","b","c"])
uT2 = uT.Conj()
print(uT)
print(uT2)
```

I was thinking to make it a global function in Cytnx, but I think a member function is also good.

**Comment by kaihsin** [comment]
I think we need this, but its not urgent

**Comment by chiamin** [comment]
Do you think we can make it before the draft is out? `Conj` is necessary for some applications so I think it is better to have it before the draft is out.

**Comment by kaihsin** [comment]
How about transpose and dagger? Those are ill-defined for normal tensor

**Comment by jeffry1829** [comment]
#207
