### ISSUE TITLE
Make linear algebra methods to support UniTensor

### ISSUE THREAD

**Issue by chiamin** [Cytnx-dev/Cytnx#196]
I checked the other Linear algebra functions (https://kaihsinwu.gitlab.io/Cytnx_doc/guide/linalg.html) and here is a list I think we can make them to but so far do not support UniTensor: Inv, InvM, Norm.

**Comment by kaihsin** [comment]
I think Inv is elementwise, and it's not physical when you have a Block diagonalize structure because the zeros are non-invertable

**Comment by chiamin** [comment]
Oh then we should not worry about Inv and InvM. How about Norm?

**Comment by kaihsin** [comment]
yes. currently those are the member function, UniTensor.Norm()

**Comment by chiamin** [comment]
OK then we just need to document it. I will close the issue.
