### ISSUE TITLE
Contracts without giving names when using optimal=True

### ISSUE THREAD

**Issue by chiamin** [Cytnx-dev/Cytnx#200]
Currently, the `Contracts` function requires every tensor to have a name in order to define the `order` argument. However, in principle, if the argument `optimal=True`, users should not need to give the `order` argument, and thus no need to set up the names. I suggest the following.

1. Set `optimal=True` as default.
2. Require tensors to be named only when `optimal=False`. In this case, `order` must be defined.

In this way, the following code should work, but currently it will raise an error.

```
import cytnx
A = cytnx.UniTensor(cytnx.ones([2,2]), labels=["i","j"])
B = cytnx.UniTensor(cytnx.ones([2,2]), labels=["j","k"])
C = cytnx.Contracts([A, B])
```

The error message is
```
Traceback (most recent call last):
  File "/home/chiamin/project/2023/cytnx/test.py", line 4, in <module>
    C = cytnx.Contracts([A, B])
RuntimeError: 
# Cytnx error occur at virtual cytnx::UniTensor cytnx::RegularNetwork::Launch(const bool&, const std::string&)
# error: [ERROR][Launch][RegularNetwork] tensor at [0], name: [] is not set.

# file : /home/kaihsinwu/.pyenv/versions/anaconda3-5.3.1/conda-bld/cytnx_1689515964188/work/src/RegularNetwork.cpp (697)
```

I suggest not touching on the current implementation of `Contract` and `Contracts`, but just renaming them and defining another `Contract` function as a wrapper to call one of the old `Contract` or `Contracts` in a proper way.

**Comment by chiamin** [comment]
To give you a concrete reason why I have this suggestion, I a writing an example for SVD

```
import cytnx
# Create a rank-3 Tensor object with shape [2,2,2]
T = cytnx.arange(2*2*2).reshape(2,2,2)
# Convert it to a UniTensor
uT = cytnx.UniTensor(T, labels=["a","b","c"])
# 1. Permute the indices to ("c","a","b") ordering,
uT.permute_(["c","a","b"])
# 2. Set rowrank=1, so that "c" is the row index,
# and "a", "b" are the column indices.
uT.set_rowrank(1)
uT.print_diagram()

S, U, Vdag = cytnx.linalg.Svd (uT, is_UvT=True)

uT2 = cytnx.Contracts ([S,U,Vdag])  # This is what I want but will raise error
```

It is annoying to either call `Contract` twice or give names to all the tensors.

**Comment by kaihsin** [comment]
I think it's the way contracts is implemented. It use network as backend, but forgot to check in the case when input tensor doesn't have name.

It should temporary give it a name before handing to backend
