### ISSUE TITLE
Svd_truncate, the returned value when return_err=True

### ISSUE THREAD

**Issue by chiamin** [Cytnx-dev/Cytnx#202]
When running `Svd_truncate` with argument `return_err=True`, it will return the largest singular value that is truncated. I suggest to return all the truncated singular values. In DMRG the truncation error is defined by summing all the truncated p_i=s_i*s_i where s_i is the singular value. In this way we can compute the truncation error.

**Comment by kaihsin** [comment]
I suggest to extend the return_err:


return_err="full" (or simply a integer ) will return all the truncated eigenvalues, for example
