### ISSUE TITLE
Remove Save/Load file extension

### ISSUE THREAD

**Issue by chiamin** [Cytnx-dev/Cytnx#204]
If I save a `Bond` object to a file "test"

```
import cytnx
bond = cytnx.Bond(10)
bond.Save('test')
```

the file name will be  "test.cybd". I suggestion to remove the file extension ".cybd" and letting the users completely decide the file name. The same for Save/Load other types in Cytnx.

**Comment by chiamin** [comment]
Then I suggest using the same file extension for all types so that we don't
need to keep remembering them for different types.

Kai-Hsin Wu ***@***.***> 於 2023年7月25日 週二 下午6:38寫道：

**Comment by kaihsin** [comment]
It's a double check, it will be very confusing if we don't have different
file extension for different things, otherwise how do you know whether the
file is a Bond/Tensor or something else?

**Comment by chiamin** [comment]
I would suggest to let users take care of that. And it is easier for maintaining the documentation. This is of course just a personal preference. I will close this one and just let me know if you want to change it.
