### ISSUE TITLE
Define Network

### ISSUE THREAD

**Issue by chiamin** [Cytnx-dev/Cytnx#205]
Can someone tell me why the following Network string doesn't work and how to fix it?

```
import cytnx
net = cytnx.Network()
net.FromString(["M1: i, j",\
                "M2: j, k",\
                "M3: k, l",\
                "TOUT: a, b",\
                "ORDER: ((M1,M2),M3)"])
```

I found it difficult to debug a Network string. Maybe we need more explanation or better error messages. Here is the error message.

```
Traceback (most recent call last):
  File "/home/chiamin/project/2023/cytnx/test.py", line 3, in <module>
    net.FromString(["M1: i, j",\
RuntimeError: 
# Cytnx error occur at void cytnx::_parse_TOUT_line_(std::vector<std::__cxx11::basic_string<char> >&, cytnx_uint64&, const std::string&, const cytnx_uint64&)
# error: [ERROR][Network][Fromfile] line:3 Invalid TOUT line

# file : /home/kaihsinwu/.pyenv/versions/anaconda3-5.3.1/conda-bld/cytnx_1689515964188/work/src/RegularNetwork.cpp (39)
```

**Comment by kaihsin** [comment]
Because a,b are not exist.

**Comment by chiamin** [comment]
So TOUT should include the remaining indices from the input tensors? In this case "i" and "l"? If this is the case, I don't understand why we need to set it because it is automatically decided.

I actually have another confusion. Do the labels in TOUT need to be separated by ";"?

In any case I think how to setup TOUT is not clear enough in User Guild.
https://kaihsinwu.gitlab.io/Cytnx_doc/guide/contraction/network.html

**Comment by kaihsin** [comment]
What do you mean automatically decided. the order is automatically decided,
not the label. We don't relabel the output.

the label of TOUT is the remainder of whatever the labels not contracted.

It's very ambiguous for the example you give, for example how should I know
which remainder bond to relabel a,b to?

**Comment by chiamin** [comment]
> the label of TOUT is the remainder of whatever the labels not contracted

Aren't they already known even if I don't specify them? In my case they are i and l, right?

And do I need to use ";" to separate the labels? Can I use ","?

> It's very ambiguous for the example you give, for example how should I know
> which remainder bond to relabel a,b to?

I thought we also inherit the order from the input. In my example, I was thinking i and l will be relabeled to a and b. But I acutally don't like this design and I think an additional line to relabel the output tensor will be clearer. So my main confusing is just the purpose of TOUT. It seems not necessary to me.

**Comment by kaihsin** [comment]
They are know, but their ORDER of output is unknow!

**Comment by kaihsin** [comment]
To make it a bit more clear:

1. If you inherit the order from the input, then the order when user write network file (i.e. which tensor should be put in the first line will be strongly coupled to the output order), and this is even more confusing/ less flexible then current design! Current design, user doesn't need to care about the order when I write network file. I just put the final shape of my UniTensor as TOUT and thats it. 

2. additional line means you separate an operation that can be specify in one line into two line, then TOUT really does nothing

3. its better for TOUT to be respect the remainder labels, and the order is specify by the TOUT, where the user can expect the output tensor bond should be in some concrete order, and change labels easily afterward.

**Comment by chiamin** [comment]
OK so TOUT is used to specify the order of the indices. That makes sense.

Another question, should I use ";" or can I just use ","? I suppose ";" is to define the rowrank, but since changing rowrank costs nothing (I suppose), I suggest just using "," and letting users change rowrank afterward.

**Comment by kaihsin** [comment]
we use "," (comma) for separate labels, and ";" (semi-colon) for rowrank

**Comment by chiamin** [comment]
Thanks for the additional explanation. I agree that setting TOUT can save one time of permutation and it makes sense to use it.

Regarding ";", I have another suggestion. The following code does not work

```
import cytnx
net = cytnx.Network()
net.FromString(["M1: i, j",\
                "M2: j, k",\
                "M3: k, l",\
                "TOUT: i, l",\
                "ORDER: ((M1,M2),M3)"])
```

It seems that I have to use one ";" in TOUT. I suppose the above code should also work by setting all the indices row indices? The main purpose is that the users can define a network without knowing the concept of rowrank.

**Comment by kaihsin** [comment]
I think we have similar discussion before. If I remember correctly, we can auto detect from the number of total remainder in-bond/ outbond (for tensors with directional bonds) or total remainder bonds via rowrank (for tensors without directional bonds) to auto assign the rowrank as a default
