### ISSUE TITLE
Need Save/Load functions for Network

### ISSUE THREAD

**Issue by chiamin** [Cytnx-dev/Cytnx#206]
Currently Network has no Save/Load functions and we should add them.

**Comment by kaihsin** [comment]
Why do you need to save a network? It's only the network file that need to be saved. The network itself has no property at all. It's just a helper class.

**Comment by chiamin** [comment]
I may want to define a network by a string and then save it to reuse it.
Ideally every object should be able to be saved and loaded.

Kai-Hsin Wu ***@***.***> 於 2023年7月25日 週二 下午6:41寫道：

**Comment by kaihsin** [comment]
That's the network file! It's like you don't "save a function" and reuse
it.

Network, even though it's a class it's not an storage object

**Comment by kaihsin** [comment]
Network.Savefile() to save the network file
Network.Loadfile() will read from the file

**Comment by chiamin** [comment]
OK Savefile and Fromfile are good enough.
