### ISSUE TITLE
GPU adding for non contiguous UniTensor still not support.

### ISSUE THREAD

**Issue by hunghaoti** [Cytnx-dev/Cytnx#210]
We may need to implement non contiguous adding for UniTensor.

**Comment by kaihsin** [comment]
whats the status of this? There is no PR merged

**Comment by jeffry1829** [comment]
This should be resolved by previous gpu branch merging

**Comment by kaihsin** [comment]
Please tag the corresponding Branch if it's not merged via PR, feel free to
close it.

**Comment by jeffry1829** [comment]
done in #217
