### ISSUE TITLE
cuGeSvd wrong recompose

### ISSUE THREAD

**Issue by jeffry1829** [Cytnx-dev/Cytnx#218]
in branch gpu
```
The following tests FAILED:
        422 - Gesvd.gpu_U1_sym_test (Failed)
        423 - Gesvd.gpu_Z2_sym_test (Failed)
        424 - Gesvd.gpu_Z3_sym_test (Failed)
        425 - Gesvd.gpu_U1xZ2_sym_test (Failed)
        428 - Gesvd.gpu_none_isU_isVT (Failed)
```

**Comment by kaihsin** [comment]
This is issue with gesvd and gesvdp. As per discussion, I am very skeptical on using gesvdp considering the control of error is hard there even tho its faster than gesvd

**Comment by jeffry1829** [comment]
I think it's best to use MAGMA gesdd by default. If not feasible, we can use Gesvd by default.
However, Gesvd is too slow for gpu as I saw on internet, and I can't figure out why it doesn't work

**Comment by jeffry1829** [comment]
This issue is now stuck in the problem that, when using cusolver gesvd, if input tensor of dimension (m,n), if m<n, we now transpose the input tensor first, then pass into the api.
We need to find an efficient way that we do not need to do the transpose

**Comment by jeffry1829** [comment]
cusolver gesvd is not used anymore
