### ISSUE TITLE
Error when using relabels_ instead of set_labels

### ISSUE THREAD

**Issue by manuschneider** [Cytnx-dev/Cytnx#228]
The function `set_labels` was replaced by `relabels_` to make the naming convention more intuitive. Therefore, I replaced `set_labels` everywhere in the user guide by `relabels_`.
However, it seems that the two functions behave differently and the code in the user guide does not run. An example from `7.1. Print and display`:

The old code works:
```
uT=cytnx.UniTensor(cytnx.ones([2,3,4]), name="untagged tensor").set_labels(["a","b","c"])
uT.print_diagram()
```
Output:
```
-----------------------
tensor Name : untagged tensor
tensor Rank : 3
block_form  : False
is_diag     : False
on device   : cytnx device: CPU
          ---------     
         /         \    
   a ____| 2     3 |____ b
         |         |    
         |       4 |____ c
         \         /    
          ---------     
```

New version:
```
uT=cytnx.UniTensor(cytnx.ones([2,3,4]), name="untagged tensor").relabels_(["a","b","c"])
uT.print_diagram()
```
Error:
```
---------------------------------------------------------------------------
AttributeError                            Traceback (most recent call last)
Cell In[62], line 2
      1 uT=cytnx.UniTensor(cytnx.ones([2,3,4]), name="untagged tensor").relabels_(["a","b","c"])
----> 2 uT.print_diagram()

AttributeError: 'NoneType' object has no attribute 'print_diagram'
```

**Comment by kaihsin** [comment]
Yes. Originally set_labels will return self, while relabel does not. We should change it by returning self. 

Part of this should be handled on python side

**Comment by manuschneider** [comment]
Ah, this was the problem, I see. I changed the guide not to use return values anymore. The above example can be done much cleaner anyways since issue #178 was solved: the UniTensor creator allows for an argument `labels`:
```
uT=cytnx.UniTensor(cytnx.ones([2,3,4]), name="untagged tensor", labels=["a","b","c"])
uT.print_diagram()
```
I changed the guide everywhere accordingly.

**Comment by kaihsin** [comment]
I pushed a PR address this issue. It should be fixed now, with a caveat
that one need to specify keywords "new_labels", "old_labels" explicitly
when two arguments are given simultaneously.
