### ISSUE TITLE
relabel several indices by their label name: relabels(old_labels=[...], new_labels=[...]}

### ISSUE THREAD

**Issue by manuschneider** [Cytnx-dev/Cytnx#232]
The syntax
```
relabels(_)(old_labels=[...], new_labels=[...]}
```
would allow to relabel several indices at a time by specifying the old labels. Up to now, the index order still needs to be known when using relabels.

One can still decide if ALL labels need to be relabeled at once or just as many as given by the list length.

**Comment by kaihsin** [comment]
I think that's the current behavior

**Comment by manuschneider** [comment]
I saw it, seems I checked an older version of the API documentation where it was not listed.
Thanks, this is very helpful.
