### ISSUE TITLE
The Svd_truncate is extremely slower than Svd in gpu version.

### ISSUE THREAD

**Issue by hunghaoti** [Cytnx-dev/Cytnx#239]
As title, 

>Svd with D=500 on gpu:  87 ms
>Svd_truncate with D=100 on gpu:  11818 ms

you can reproduce by running the following code and adjust the bond dimension.
https://github.com/Cytnx-dev/Cytnx/blob/dffe31ddb6965d11f681d9c69115bf552a43a0ae/bm_tests/linalg/Svd_truncate_bm.cpp#L49-L59
https://github.com/Cytnx-dev/Cytnx/blob/dffe31ddb6965d11f681d9c69115bf552a43a0ae/bm_tests/linalg/Svd_bm.cpp#L83-L93

**Comment by kaihsin** [comment]
@hunghaoti  have you managed to test this yet?

**Comment by hunghaoti** [comment]
> @hunghaoti have you managed to test this yet?

Hi @kaihsin 
for bond dimension d*D= [10, 100, 200, 400, 600, 800, 1000, 2000, 5000]
The bench mark test results as following (on A100 GPU):
for this commit: a18c307a0624c3a420377960db802121acabdfce (the original version)
time = [5.94, 662, 11818, X, X, X, X, X, X] ms

for this commit: c1d4bc665daa311aaea76e350694ae00ae1edaea (using cuQuantum)
time = [5.09, 9.79, 18.1, 41.3, 70.2, 109, 157, 640, 6919] ms

for this commit: a3f7ce3a09ac82337520f06d51fa48d2800c4d6f (after merge to dev-master)
time = [5.58, 11.3, 20.4, 46.1, 77.0, 118, 169, 666, 7049] ms

 I think this issue can be close if there is no problem.

**Comment by kaihsin** [comment]
Cool thanks!
