### ISSUE TITLE
cuquantum cmake file need to be fixed

### ISSUE THREAD

**Issue by hunghaoti** [Cytnx-dev/Cytnx#240]
For the latest version of cuquantum, if we download the tarball of it, the structure has been changed see ([here](https://developer.nvidia.com/cuquantum-downloads?target_os=Linux&target_arch=x86_64&Distribution=Agnostic&cuda_version=12))
 as
ququantum_root/lib/libXXX.so instead of ququantum_root/lib/12/libXXX.so

So the following code need to be change or find another proper way to rewrite:
https://github.com/Cytnx-dev/Cytnx/blob/2dc99bd7f01b881fde60d36cece8ece311acdb9f/cmake/Modules/FindCUQUANTUM.cmake#L29-L38

**Comment by kaihsin** [comment]
Follow the one on conda
