### ISSUE TITLE
Whenever we create a new UniTensor, provide an optional argument to initialize the name.

### ISSUE THREAD

**Issue by pcchen** [Cytnx-dev/Cytnx#241]
Now we can do this to initialize UniTensors' name:
````
A = cytnx.UniTensor(cytnx.ones([2,2,2]), name="A", labels=["alpha","beta","gamma"])
B = cytnx.UniTensor(cytnx.ones([2,2]), name="B", labels=["beta","delta"])
C = cytnx.UniTensor(cytnx.ones([2]), name="C", labels=["gamma"])
````
But when we do this
````
AB = cytnx.Contract(A, B)
````
If we want AB to have the name "AB", we need to do it separately.

I would suggest that whenever we create a new UniTensor, we provide an optional argument to initialize the name. For example
````
AB = cytnx.Contract(A, B, name="AB")
````

**Comment by kaihsin** [comment]
I think the best way is to let Unitensor.set_name() return self, 

So one can do chain action like


```python 

C = contract(A,B).set_name("c")

```

**Comment by pcchen** [comment]
Thanks. I think Unitensor.set_name() can do the job.
