### ISSUE TITLE
Gesvd issue

### ISSUE THREAD

**Issue by hunghaoti** [Cytnx-dev/Cytnx#245]
I would like to ask whether we should use get_block() instead of get_block_().
Since it looks like it will change the data in `Tin`.
https://github.com/Cytnx-dev/Cytnx/blob/c1d4bc665daa311aaea76e350694ae00ae1edaea/src/linalg/Gesvd.cpp#L92-L92
https://github.com/Cytnx-dev/Cytnx/blob/c1d4bc665daa311aaea76e350694ae00ae1edaea/src/linalg/Gesvd_truncate.cpp#L89-L89

You can reproduce be the following code:
```c++
int D = 10;
auto bd_vi = Bond(D, BD_IN);
auto bd_pi = Bond(2, BD_IN);
auto bd_po = Bond(2, BD_OUT);
auto bd_vo = Bond(D, BD_OUT);
std::vector<Bond> bonds = {bd_vi, bd_pi, bd_po, bd_vo};
cytnx_int64 row_rank = 2;
std::vector<std::string> labels = {};
bool is_diag = false;
auto UT = UniTensor(bonds, labels, row_rank, Type.Double, Device.cuda, is_diag);
double low = -1000, high = 1000;
int rnd_seed = 0;
random::Make_uniform(UT, low = -1000, high = 1000, rnd_seed);
std::cout << UT;
std::vector<UniTensor> svds = linalg::Gesvd_truncate(UT, D);
std::cout << UT;

```

**Comment by jeffry1829** [comment]
This will be fixed in the next commit, seems like in Gesvd_truncate(cuquantum version), we didn't reshape_ tmp Tensor to its original shape

**Comment by hunghaoti** [comment]
I have checked this issue and it is solved.
