### ISSUE TITLE
cytnx.linalg.Eigh

### ISSUE THREAD

**Issue by pcchen** [Cytnx-dev/Cytnx#246]
It seems that if one do 
````
E, U = cytnx.linalg.Eigh(cytnx.Tensor)
````
then `E` is a `cytnx.Tensor` which contains all eigenvalues.

If one do
````
E = cytnx.linalg.Eigh(cytnx.Tensor, is_V=False)
````
then `E` is a list and `E[0]` is a `cytnx.Tensor` which contains all eigenvalues.

I think this is no so consistent.

**Comment by kaihsin** [comment]
Eigh always returns a list regardless of whether is_V=True or False

**Comment by pcchen** [comment]
Thanks.

**Comment by kaihsin** [comment]
```python
[ E , V ] = Eigh(Tensor) 
[E] = Eigh(Tensor, is_V=False)
```

**Comment by pcchen** [comment]
Thanks. I realize that I try to unpack the result into a tuple so I got confusing results.
