### ISSUE TITLE
The type of shape and reshape not consistent

### ISSUE THREAD

**Issue by hunghaoti** [Cytnx-dev/Cytnx#289]
In UniTensor API, shape() return `std::vector<cytnx_uint64>` but the input argument of reshape(...) is `std::vector<cytnx_int64>`.

**Comment by kaihsin** [comment]
I believe this is intentional because the input allows the user to specify (-1) for at most one undetermined axis like python

**Comment by hunghaoti** [comment]
I see, if there is no problem then I will close this issue.
