### ISSUE TITLE
at() cannot be called with indices anymore

### ISSUE THREAD

**Issue by manuschneider** [Cytnx-dev/Cytnx#294]
I tried the following code from the draft and it did not work, it seems at() can ONLY be called with labels at the moment
# 1. Create a complex UniTensor by Tensor
T = cytnx.zeros([2,2], dtype=cytnx.Type.ComplexDouble)
uT = cytnx.UniTensor(T, labels=["a","b"], name="uT")
# Set an element to a complex number
uT.at([0,0]).value = 1+1j

**Comment by jeffry1829** [comment]
This will be fixed once #291 is merged
