### ISSUE TITLE
cannot call on a un-initialize UniTensor_base

### ISSUE THREAD

**Issue by yaotingsu** [Cytnx-dev/Cytnx#308]
Hi,
I tried to run DMRG and got the following error:

RuntimeError: 
# Cytnx error occur at virtual bool cytnx::UniTensor_base::is_blockform() const
# error: [ERROR] fatal internal, cannot call on a un-initialize UniTensor_base

**Comment by manuschneider** [comment]
This error did not occur in version 0.9.2 but it does in v0.9.5. Was is_blockform() removed for UniTensors?

**Comment by j9263178** [comment]
> This error did not occur in version 0.9.2 but it does in v0.9.5. Was is_blockform() removed for UniTensors?

There are some API changes in the `Network` and the example codes are not updated, we will fix them soon.

**Comment by j9263178** [comment]
@yaotingsu  @manuschneider  Which DMRG codes that your are running?

**Comment by j9263178** [comment]
> @yaotingsu @manuschneider Which DMRG codes that your are running?

ok it seems like it's the NCTS summer school code.
