### ISSUE TITLE
Urgent: Hiding Tensors

### ISSUE THREAD

**Issue by pcchen** [Cytnx-dev/Cytnx#314]
We want to hide `Tensor` to physics UniTensor user.

* [x] Generators for (dense) UniTensor, example, cytnx.UniTensor.ones(), cytnx.UniTensor.random(), etc.
* [ ] Add get_Block_UniTensor().
* [ ] Fix put_Block and also allow put_Block to accept dense UniTensor.

**Comment by pcchen** [comment]
Please help to make sure that following codes are supported.
````
A = cytnx.UniTensor([2,3])
auto A = cytnx::Uni
A = cytnx.UniTensor.ones([8,2,8], labels=["v1","phy","v2"], name="A")
uT = cytnx.UniTensor.arange([2,3,4], labels=["a","b","c"], name="tensor uT")
uT = cytnx.UniTensor.zeros([2,2], dtype=cytnx.Type.ComplexDouble,labels=["a","b"], name="uT")
rT = cytnx.UniTensor.random.uniform([2,3,2], low=0., high=1.)
````

**Comment by hunghaoti** [comment]
> Please help to make sure that following codes are supported.
> 
> ```
> A = cytnx.UniTensor([2,3])
> auto A = cytnx::Uni
> A = cytnx.UniTensor.ones([8,2,8], labels=["v1","phy","v2"], name="A")
> uT = cytnx.UniTensor.arange([2,3,4], labels=["a","b","c"], name="tensor uT")
> uT = cytnx.UniTensor.zeros([2,2], dtype=cytnx.Type.ComplexDouble,labels=["a","b"], name="uT")
> rT = cytnx.UniTensor.random.uniform([2,3,2], low=0., high=1.)
> ```

The following codes are supported for this PR #316 
```python

A = cytnx.UniTensor.ones(shape = [8,2,8], labels=["v1","phy","v2"], name="A")
uT = cytnx.UniTensor.arange(Nelem = 8, labels=["a"], name="tensor uT")
uT = cytnx.UniTensor.zeros(shape = [2,2], dtype=cytnx.Type.ComplexDouble,labels=["a","b"], name="uT")
rT = cytnx.UniTensor.uniform(shape = [2,3,2], low=0., high=1.)

```

**Comment by manuschneider** [comment]
It would be great if `UniTensor.eye()` would also be supported, `eye` is used in the draft.

**Comment by kaihsin** [comment]
again , I still think tensor.eye().unitensor() will be the best syntax. I will do this modification in the next version very soon, and once it's done it might as well get deprecated later.
