### ISSUE TITLE
get() set() for UniTensor

### ISSUE THREAD

**Issue by manuschneider** [Cytnx-dev/Cytnx#319]
At the moment, the elements of a UniTensor can only be accessed by
1) .at(), which only returns one element
2) accessing the block (Tensor) and then the data

Since we want to avoid dealing with Tensors, it would be great if get() and set() can be supported, at least for dense UniTensor.

Sugar code like uT[0,:,1:4:2] would be amazing for UniTensors as well, but for the paper we need at least get() and set().

**Comment by kaihsin** [comment]
get and set us already there

**Comment by pcchen** [comment]
What is the syntax of get() and get() for UniTensor? (If it exists.)

**Comment by j9263178** [comment]
> What is the syntax of get() and get() for UniTensor? (If it exists.)

Currently it has no pybind API, will add them soon.

**Comment by j9263178** [comment]
> What is the syntax of get() and get() for UniTensor? (If it exists.)

@manuschneider  @pcchen I think things like `Ut[:, 0:1, 1]`  should already work in python.

**Comment by pcchen** [comment]
On which branch and after which commit?

**Comment by pcchen** [comment]
OK. It seems to work for me with version 0.9.5.

**Comment by pcchen** [comment]
This works 
````
UT1 = cytnx.UniTensor(cytnx.arange(4*4*4).reshape(4,4,4),labels=["a","b","c"])
UT2 = cytnx.UniTensor(cytnx.arange(8*8*8).reshape(8,8,8),labels=["a","b","c"])
print(UT1[1:3,2,3])
print(UT2[1:3,2,3])
````

But these will fail (for Tensor it works)
````
UT1[1,2,3] = -1.0
UT1[1:3,2,3] = UT2[1:3,2,3]
````

**Comment by j9263178** [comment]
> This works
> 
> ```
> UT1 = cytnx.UniTensor(cytnx.arange(4*4*4).reshape(4,4,4),labels=["a","b","c"])
> UT2 = cytnx.UniTensor(cytnx.arange(8*8*8).reshape(8,8,8),labels=["a","b","c"])
> print(UT1[1:3,2,3])
> print(UT2[1:3,2,3])
> ```
> 
> But these will fail (for Tensor it works)
> 
> ```
> UT1[1,2,3] = -1.0
> UT1[1:3,2,3] = UT2[1:3,2,3]
> ```

The last two lines should work now in the corresponding PR, plx build and check.

**Comment by pcchen** [comment]
This is to confirm that last two lines work in the corresponding PR.

**Comment by manuschneider** [comment]
I cannot compile the branch `ut_slice_set`.
I get lots of `GOMP` related errors like
```
Complexmem_cpu.cpp:49: undefined reference to `GOMP_loop_ull_nonmonotonic_dynamic_start'
```

**Comment by j9263178** [comment]
> `GOMP_loop_ull_nonmonotonic_dynamic_start'

@manuschneider  What's your `Install.sh`? and can you compile `dev-master` succesfully under the same configuration?

**Comment by manuschneider** [comment]
These are all the flags that are set:
```
FLAG="${FLAG} -DBACKEND_TORCH=OFF"
FLAG="${FLAG} -DUSE_MKL=ON"
FLAG="${FLAG} -DBUILD_PYTHON=ON"
FLAG="${FLAG} -DUSE_HPTT=OFF "
FLAG="${FLAG} -DHPTT_ENABLE_FINE_TUNE=ON"
FLAG="${FLAG} -DHPTT_ENABLE_AVX=ON"
FLAG="${FLAG} -DUSE_CUDA=ON "  #same problem without CUDA
FLAG="${FLAG} -DUSE_CUTT=off "
FLAG="${FLAG} -DCUTT_ENABLE_FINE_TUNE=off "
FLAG="${FLAG} -DUSE_MAGMA=OFF "
FLAG="${FLAG} -DUSE_CUTENSOR=OFF "
FLAG="${FLAG} -DUSE_CUQUANTUM=OFF "
FLAG="${FLAG} -DCMAKE_EXPORT_COMPILE_COMMANDS=1 "
FLAG="${FLAG} -DUSE_OMP=OFF"
FLAG="${FLAG} -DRUN_TESTS=ON "
```

`dev-master` compiles without problems with the same `Install.sh`.

The errors occur at `Built target pycytnx` and then during the linking.

**Comment by j9263178** [comment]
> These are the flags that are set:
> 
> ```
> FLAG="${FLAG} -DBACKEND_TORCH=OFF"
> FLAG="${FLAG} -DUSE_MKL=ON"
> FLAG="${FLAG} -DBUILD_PYTHON=ON"
> FLAG="${FLAG} -DUSE_HPTT=OFF "
> FLAG="${FLAG} -DHPTT_ENABLE_FINE_TUNE=ON"
> FLAG="${FLAG} -DHPTT_ENABLE_AVX=ON"
> FLAG="${FLAG} -DUSE_CUDA=ON "  #same problem without CUDA
> FLAG="${FLAG} -DUSE_CUTT=off "
> FLAG="${FLAG} -DCUTT_ENABLE_FINE_TUNE=off "
> FLAG="${FLAG} -DUSE_MAGMA=OFF "
> FLAG="${FLAG} -DUSE_CUTENSOR=OFF "
> FLAG="${FLAG} -DUSE_CUQUANTUM=OFF "
> FLAG="${FLAG} -DCMAKE_EXPORT_COMPILE_COMMANDS=1 "
> FLAG="${FLAG} -DUSE_OMP=OFF"
> FLAG="${FLAG} -DRUN_TESTS=ON "
> ```
> 
> `dev-master` compiles without problems with the same `Install.sh`.
> 
> The errors occur at `Built target pycytnx` and then during the linking.

@manuschneider Currently I'm not sure what is going on and I cannot reproduce it, plx check that you did `rm -rf build` before a new build, also try turn on the hptt.

**Comment by manuschneider** [comment]
Thanks, I could compile now in the newest version of the branch.
I can confirm that `set_elem()`, `get_elem()` and slicing like `uT[0,:,2:4]` works.

**Comment by j9263178** [comment]
I reopend this since currently the behavior for  `is_diag=True`  ut is not handled properly.

**Comment by kaihsin** [comment]
This is resolved, we don't allow any is_diag tensor to be incoming/receiving. The user need to convert to Dense via .to_dense()
