### ISSUE TITLE
print_block, get_block, put_block

### ISSUE THREAD

**Issue by pcchen** [Cytnx-dev/Cytnx#341]
First, print_block will print each block as a UniTensor. In you get_block then print, you print a tensor. This is the current behavior, we should discuss this in the future.

Second, can we let print_block accept similar argument in get_block, put_block. Like print_block([0,1,1]), print_block("a","b","c"],[1,1,1]).

What is the difference between Qn index (quantum number index) and a list of quantum numbers?

**Comment by kaihsin** [comment]
Qn index is the index of a list of quantum numbers
