### ISSUE TITLE
linalg.Eig,Eigh do not support symmetric UniTensor?

### ISSUE THREAD

**Issue by pcchen** [Cytnx-dev/Cytnx#345]
I got something like this
````
# Cytnx error occur at std::vector<cytnx::UniTensor> cytnx::linalg::Eig(const cytnx::UniTensor&, const bool&, const bool&)
# error: [ERROR] Eig, unsupported type of UniTensor only support (Dense). something wrong internal
````

This is  by design? or this is something TODO?

**Comment by j9263178** [comment]
They are not implemented for block and sparse ut in current version.

**Comment by pcchen** [comment]
Please implement it. (Eig, Eigh, InvM, InvM_, anything else?) Since we talk about Eigh in SciPost.

**Comment by chiamin** [comment]
Can someone implement them?
