### ISSUE TITLE
Print UniTensor.shape

### ISSUE THREAD

**Issue by chiamin** [Cytnx-dev/Cytnx#349]
When print a UniTensor.shape, it will print also the elements. Can we change to only printing the shape as well as its index labels? Something like `(label1, label2, label3) = (3,2,3)`.

**Comment by j9263178** [comment]
Printing `UniTensor.shape()` will not print out the element.

**Comment by j9263178** [comment]
`.shape()` should only contain the shape information as its name suggeset. 

If one wants the corresponding labels one can print `.labels()`.

If you really want to display these infos together you can also try `.print_diagram()`.
