### ISSUE TITLE
Dagger, Transpose documentation

### ISSUE THREAD

**Issue by chiamin** [Cytnx-dev/Cytnx#384]
I couldn't find Dagger and Transpose for UniTensor in the documentation. If it is indeed not there, we need to add them and especially explain the different behaviors of Transpose for symmetric and non-symmetric UniTensor.

**Comment by j9263178** [comment]
It is  in 7.9. Manipulate UniTensor.

**Comment by chiamin** [comment]
Thanks. Somehow I missed it.
