### ISSUE TITLE
Bugs in Movemem_cpu.cpp?

### ISSUE THREAD

**Issue by TensorNetwork18** [Cytnx-dev/Cytnx#405]
Dear Cyten developers,

In dev-master branch, I somehow was not able to compile with -DUSE_OMP=ON.
From the error message, the vector shifter_old has not been properly initialized before use in some places.

After adding shifter_old as follows,
```       
      std::vector<cytnx_int64> shifter_new(old_shape.size());
      std::vector<cytnx_int64> shifter_old(old_shape.size());

      for (cytnx_int64 i = old_shape.size() - 1; i >= 0; i--) {
        shifter_old[i] = accu_old;
        shifter_new[i] = accu_new;
        accu_old *= old_shape[i];
        accu_new *= newshape[i];
      }    
```
 I was able to get it to compile.

But, I don't really know what's going on.. 
If I'm doing something incorrect, let me know.

Best,
Jheng-Wei Li

**Comment by jeffry1829** [comment]
It’ll be fixed as soon as possible, thanks!
