### ISSUE TITLE
compile error on windows!

### ISSUE THREAD

**Issue by jcyhcs** [Cytnx-dev/Cytnx#423]
Tensor libraries\Cytnx\src\UniTensor_base.cpp(451) : error C4716: “cytnx::UniTensor_base::at_for_sparse”: 必须返回一个值.
i just look inside:
  Scalar::Sproxy UniTensor_base::at_for_sparse(const std::vector<cytnx_uint64> &locator) {
    cytnx_error_msg(true, "[ERROR] fatal internal, cannot call on a un-initialize UniTensor_base%s",
                    "\n");

  }
it really didn't return a value! maybe this is a BUG!
please help me!
i use MSVC 2022 compiler

**Comment by jeffry1829** [comment]
Sorry, we don’t support windows
You may need to use WSL2 if you need to make it run on windows

This error is due to, in g++, we disabled the checking whether every function return some value.
