### ISSUE TITLE
Lanczos for multiple eigenstates

### ISSUE THREAD

**Issue by pcchen** [Cytnx-dev/Cytnx#434]
We need to add support such that Lanczos can return lowest m eigenstates, instead of just ground state.

**Comment by jeffry1829** [comment]
We can achieve that by specify Lanczos parameter method="ER", and specify parameter k

**Comment by pcchen** [comment]
Thanks. I will close this issue.

**Comment by pcchen** [comment]
Thanks. I will close this issue.
