### ISSUE TITLE
Transition to cuTENSOR 2.x

### ISSUE THREAD

**Issue by j9263178** [Cytnx-dev/Cytnx#439]
https://docs.nvidia.com/cuda/cutensor/latest/api_transition.html

There are some API changes in the new version so the current source code cannot be compiled with cuTENSOR 2.x.

**Comment by IvanaGyro** [comment]
I have finished this job that migrates cuTENSOR to 2.x. I will create a PR after getting the permission to create a new branch on this repo.

**Comment by IvanaGyro** [comment]
Done with #447
