### ISSUE TITLE
Change header guard to use #pragma once

### ISSUE THREAD

**Issue by kaihsin** [Cytnx-dev/Cytnx#470]

**Comment by IvanaGyro** [comment]
There are some decisions from the coding style guide.

- https://google.github.io/styleguide/cppguide.html#The__define_Guard
- https://google.github.io/styleguide/cppguide.html#Nonstandard_Extensions
- http://isocpp.github.io/CppCoreGuidelines/CppCoreGuidelines#sf8-use-include-guards-for-all-header-files

To summarise, prefer header guards than `#pragma once`. The former is supported by the standard and is more portable.

**Comment by kaihsin** [comment]
Are we following Google coding style now?

**Comment by kaihsin** [comment]
If so I would like to have a pre-commit tool in place for this

**Comment by IvanaGyro** [comment]
> Are we following Google coding style now?

It seems that, yes. 

https://github.com/Cytnx-dev/Cytnx/blob/f43dcbd960b955611cddcbc036cc07e113dbbb8b/.clang-format#L1

We also have pre-commit settings

https://github.com/Cytnx-dev/Cytnx/blob/f43dcbd960b955611cddcbc036cc07e113dbbb8b/.pre-commit-config.yaml

CC @jeffry1829

**Comment by kaihsin** [comment]
Does it actually settled up on action? I thought its there. And it was fine
before tho, so I am confused

**Comment by kaihsin** [comment]
If it's optional requirements for format I'd say we don't worry about it
and follow as much as std. Google style is good but it has too much
historical burdens

**Comment by IvanaGyro** [comment]
Client-side git hooks do not sync between git clients. Every client has to install the hook on their own. Here is a section of the document shared by @hunghaoti 

---

2. Use the pre-commit tool to check the coding style:

    (1). If you have not installed the pre-commit tool, you can install it by the command:
    ```bash
    conda install pre-commit
    ```
    (2). Then you can run the following command to fix the coding style:
    ```bash
    pre-commit run --all-files
    ```
    `You can run twice to make sure all of them are passed.`

**Comment by kaihsin** [comment]
Yes I know. We set up this. My point is if there is no issue with clang
formatter then I don't think we should care about the format even it stated
in Google style. In general as long as there is a guard there (which we
setup in action) beyond that norm I don't want to put focus on making style
happy. We should focus on other more important issues
