### ISSUE TITLE
Replacing magma_zgetrf_gpu by cusolverDn<Z><getrf>

### ISSUE THREAD

**Issue by yingjerkao** [Cytnx-dev/Cytnx#482]
Now that CuSolver has implemented LU decomposition 

https://github.com/NVIDIA/CUDALibrarySamples/tree/master/cuSOLVER/Xgetrf

I propose to replace `magma_zgetrf_gpu` in `cuDet_internal.cu` with `cusolverDn<Z><getrf>` 

https://docs.nvidia.com/cuda/cusolver/index.html#cusolverDnXgeqrf

With this update, we can drop the dependency on MAGMA.

**Comment by IvanaGyro** [comment]
It seems that there is an entry for magma in the git submodule.
https://github.com/Cytnx-dev/Cytnx/blob/733d434521c2ae673703cfd14f3faf154b9967ca/.gitmodules#L11

**Comment by yingjerkao** [comment]
I will clean things up in #536
