### ISSUE TITLE
cytnx.linalg.ExpM always returns complex UniTensor

### ISSUE THREAD

**Issue by chiamin** [Cytnx-dev/Cytnx#493]
`cytnx.linalg.ExpM(T)` returns a complex UniTensor even if the input tensor is real. It can be demonstrated as follows.

```
T = cytnx.UniTensor.uniform([2,2], low=0., high=1.)
Q = cytnx.linalg.ExpM(T)
print(T.dtype_str())
print(Q.dtype_str())
```

**Comment by kaihsin** [comment]
ExpM rely on diagonalization, which eigenvalues is not always real right? ExpH is the the one that can always guarantee that

**Comment by chiamin** [comment]
You are right! I will close this issue.

**Comment by ianmccul** [comment]
Well, you should be careful, that if the matrix doesn't have a complete set of real eigenvalues then diagonalization is a really terrible way of calculating the exponential!  There are much better ways of calculating the matrix exponential; I use https://www.maths.uq.edu.au/expokit/ that uses a Pade approximation.  Scipy also uses Pade.

**Comment by kaihsin** [comment]
Yes. There are also other approximation methods via iteration.
