### ISSUE TITLE
Network class dispatch question

### ISSUE THREAD

**Issue by yingjerkao** [Cytnx-dev/Cytnx#535]
In fixing issue #506, I managed to refactor `SearchTree` and `ContractionTree` with new algorithms and smart pointers. See branch https://github.com/Cytnx-dev/Cytnx/tree/fix-contraction-tree

All the tests passed except those related to Network. In order to move forward, I need to understand the Network dispatch mechanism. Here is what I understand

`Network_base` class is the interface class that the virtual functions should be pure and implemented by the derived classes such as `RegularNetwork` or `FermionicNetwork`. However, `Network` is genetic user facing API which has a constructor 
```
Network() : _impl(new Network_base()){};
```
and all the type related dispatches are determined by `network_type` in the member functions, which replaces `_impl` with pointers to `RegularNetwork` etc. 

Is my understanding correct? Also, in this way each function will create a new instance of `_impl` instead of move the original `_impl` to the current object, which might make memory management an issue?

**Comment by kaihsin** [comment]
That constructor is when user create a Network without any arguments. 
```c++
    auto x = Network(); 
    x.FromFile("mynetwork.net");
```

Generally, one use the following constructor when create a specific Network, then there is no issue 
```c++
    auto x = Network("mynetwork.net", NtType.Regular); 
```

**Comment by yingjerkao** [comment]
Then I have trouble understanding why this test fails
```
TEST_F(NetworkTest, Network_dense_no_order) {
  auto net = Network();
  net.FromString({"A: a,b,c", "B: c,d", "C: d,e", "TOUT: a,b;e"});
  net.PutUniTensors({"A", "B", "C"}, {utdnA, utdnB, utdnC});
  EXPECT_TRUE(AreNearlyEqTensor(net.Launch().get_block(), utdnAns.get_block(), 1e-12));
}
```

**Comment by kaihsin** [comment]
have you tried to print out the diff for those two tensors in comparison?

**Comment by yingjerkao** [comment]
Even this simple one fails
```
TEST_F(NetworkTest, Network_dense_FromString) {
  auto net = Network();
  net.FromString({"A: a,b,c", "B: c,d", "C: d,e", "ORDER:(A,(B,C))", "TOUT: a,b;e"});
}
```
